### ISSUE TITLE
Array response is going into handle_hal_links_embedded

### ISSUE THREAD

**Issue by lsarni** [flexirest/flexirest#100]
### Expected behaviour

When I try to get from an endpoint that returns an array of string I get this error TypeError: no implicit conversion of Symbol into Integer on [this line](https://github.com/flexirest/flexirest/blob/master/lib/flexirest/request.rb#L662) on the `if attributes[:_links]`.
It's getting there because the `Content-Type` of my response is `application/json` so `hal_response?` is `true`

Part of the error:
```
TypeError - no implicit conversion of Symbol into Integer:
  flexirest (1.5.5) lib/flexirest/request.rb:612:in `handle_hal_links_embedded'
  flexirest (1.5.5) lib/flexirest/request.rb:553:in `new_object'
  flexirest (1.5.5) lib/flexirest/request.rb:704:in `block in generate_new_object'
  flexirest (1.5.5) lib/flexirest/request.rb:703:in `generate_new_object'
  flexirest (1.5.5) lib/flexirest/request.rb:501:in `handle_response'
  config/initializers/01_flexirest.rb:7:in `handle_response'
  flexirest (1.5.5) lib/flexirest/request.rb:219:in `block (2 levels) in call'
  faraday (0.9.2) lib/faraday/response.rb:57:in `on_complete'
  flexirest (1.5.5) lib/flexirest/request.rb:200:in `block in call'
  activesupport (4.2.4) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.4) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.4) lib/active_support/notifications.rb:164:in `instrument'
  flexirest (1.5.5) lib/flexirest/request.rb:156:in `call'
  flexirest (1.5.5) lib/flexirest/mapping.rb:46:in `_call'
  flexirest (1.5.5) lib/flexirest/mapping.rb:28:in `block in _map_call'
  app/controllers/application_controller.rb:93:in `get_neighborhood_list
```

When it reaches `if attributes[:_links]` the value of `attributes` is one of the strings inside the array, so for instance: `"Ahwatukee Foothills Village"`. For this reason it throws the error.

**Maybe the problem is here:**
```ruby
def generate_new_object(options={})
   if @response.body.is_a?(Array) || @response.body.is_a?(Hash)
      body = @response.body
    elseif is_json_response?
      ....
end
```

**The `@response.body` is a string but technically it's an array:**
```
"[\"Alameda\",\"Alamo Square\",\"Albany\",\"Bayview\",\"Belmont\",\"Berkeley Hills\",\"Bernal Heights\",\"Burbank\",\"Burlingame\",\"Burlingame Terrace\",\"Castro\",\"Centennial\",\"Central Sacramento\"]"
```

### Desired behaviour

I would like to be able to handle simple Arrays as json without encountering this error. I need `hal_response?` to be false in case the response is an Array of Strings or any other simple value.

### How to reproduce

This is my model:

```ruby
class Neighborhood < BaseModel
  get :by_location, "/neighborhoods/by_location"
end
```

And I call it like this:
`@hoods = Neighborhood.by_location(city: city_to_use)`

It goes through here, but it fails on the code executed when calling `super`:
```
def handle_response(response, cached = nil)
   result = super(response, cached)
   setup_paging_variables result, response
   setup_paging_variables result.data, response if result.respond_to? 'data'
   result
 end
```

The endpoint returns:
```
[
    "Ahwatukee Foothills Village",
    "Alhambra",
    "Camelback East Village",
    "Central City",
]
```
With this headers:

![screen shot 2018-08-06 at 14 50 25](https://user-images.githubusercontent.com/15196342/43732418-13a37b58-9988-11e8-9cba-f02c0b34408b.png)

**Comment by andyjeffries** [comment]
Sorry for the delay in replying, I've been away on holiday/vacation.

Thanks for the feedback, but how would you use a class that calls this endpoint? Because normally you'd do something like:

```ruby
City.all.each do |city|
  puts city.name
end
```

But without an attribute name/object for each element in the array, there's no `.name` to call.

You could probably also achieve this using [plain requests](https://github.com/flexirest/flexirest/blob/master/docs/plain-requests.md) with something like:

```ruby
class City < Flexirest::Base
  get :all, "/v1/city", plain: true
end

JSON.parse(City.all).each do |city|
  puts city
end
```

**Comment by andyjeffries** [comment]
Closing due to inactivity.

**Comment by rgisiger** [comment]
I would like to reopen this issue since it's the same behavior I tried to address with the following [Pull Request](https://github.com/flexirest/flexirest/pull/126).
