### ISSUE TITLE
"wrong number of arguments" error at mapping

### ISSUE THREAD

**Issue by lsarni** [flexirest/flexirest#109]
### Expected behaviour

I am trying to define this inside my model
`put :update_post, '/chefs/:id/posts/:post_id', localize: true`

But I'm getting this error:

```
ArgumentError - wrong number of arguments (given 3, expected 0..1):
  flexirest (1.5.5) lib/flexirest/mapping.rb:27:in `block in _map_call'
  app/models/chef.rb:23:in `<class:Chef>'
  app/models/chef.rb:1:in `<top (required)>'
  activesupport (4.2.4) lib/active_support/dependencies.rb:457:in `load'
  activesupport (4.2.4) lib/active_support/dependencies.rb:457:in `block in load_file'
  activesupport (4.2.4) lib/active_support/dependencies.rb:647:in `new_constants_in'
  activesupport (4.2.4) lib/active_support/dependencies.rb:456:in `load_file'
  activesupport (4.2.4) lib/active_support/dependencies.rb:354:in `require_or_load'
  activesupport (4.2.4) lib/active_support/dependencies.rb:494:in `load_missing_constant'
  activesupport (4.2.4) lib/active_support/dependencies.rb:184:in `const_missing'
  activesupport (4.2.4) lib/active_support/dependencies.rb:526:in `load_missing_constant'
  activesupport (4.2.4) lib/active_support/dependencies.rb:184:in `const_missing'
  app/controllers/chefs_controller.rb:40:in `show'
  actionpack (4.2.4) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.4) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.4) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.4) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.4) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.4) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.4) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.4) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.4) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.4) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.4) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.4) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.4) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.4) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.4) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  actionpack (4.2.4) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.4) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.4) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.4) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.4) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:45:in `serve'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:821:in `call'
  lib/middleware/geo_middleware.rb:28:in `call'
  rack (1.6.10) lib/rack/etag.rb:24:in `call'
  rack (1.6.10) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.10) lib/rack/head.rb:13:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.10) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.10) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  lib/middleware/redirect_middleware/middleware.rb:146:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.4) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  airbrake (4.3.3) lib/airbrake/rails/middleware.rb:13:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  lograge (0.3.4) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  request_store (1.2.0) lib/request_store/middleware.rb:8:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.10) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.10) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack-rewrite (1.4.01) lib/rack/rewrite.rb:20:in `call'
  rack (1.6.10) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.10) lib/rack/sendfile.rb:113:in `call'
  airbrake (4.3.3) lib/airbrake/user_informer.rb:16:in `_call'
  airbrake (4.3.3) lib/airbrake/user_informer.rb:12:in `call'
  railties (4.2.4) lib/rails/engine.rb:518:in `call'
  railties (4.2.4) lib/rails/application.rb:165:in `call'
  lib/middleware/route_hacks_middleware.rb:22:in `call'
  rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
  rack-reverse-proxy (0.11.0) lib/rack_reverse_proxy/roundtrip.rb:19:in `call'
  rack-reverse-proxy (0.11.0) lib/rack_reverse_proxy/middleware.rb:25:in `call'
  rack (1.6.10) lib/rack/content_length.rb:15:in `call'
  puma (3.6.0) lib/puma/configuration.rb:225:in `call'
  puma (3.6.0) lib/puma/server.rb:578:in `handle_request'
  puma (3.6.0) lib/puma/server.rb:415:in `process_client'
  puma (3.6.0) lib/puma/server.rb:275:in `block in run'
  puma (3.6.0) lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```

I have tried:
`put :update_post, '/chefs/:id/posts/:post_id'`
`put :update_post, '/chefs/:id/posts'`
But I get the same or a similar error.

If I change it to a `get` it works:
 `get :update_post, '/chefs/:id/posts', localize: true`
But it's not what I need.

Any ideas? I'm using version 1.5.5

**Comment by andyjeffries** [comment]
When do you get the error, when calling it? Can you share the calling code?

I can definitely define that method with:

```ruby
class Chef < Flexirest::Base
  put :update_post, '/chefs/:id/posts/:post_id', localize: true
end
```

**Comment by lsarni** [comment]
The calling code is:

`@chef = Chef.find({ id: chef_id, auth_token: auth_token })`

Which is unexpected, but that's what I'm seeing from the error trace.

This is where the `Chef.find` is defined:

class Chef < BaseModel
  include LocalizeURL
  include GenericData
  extend ActiveModel::Naming

  # finders
  get :all,  "/chefs"
  get :find, "/chefs/:id"
  put :put,  "/chefs/:id"

  # search
  get :search,   "/search/chefs", localize: true

  # helpers
  get :by_venue, "/venues/:venue_id/chefs"
  get :associated_content, "chefs/:id/associated_content"

  get :chef_names, '/chefs/chef_names'
  post :application, '/chefs/expert_application'
  post :post, '/chefs/:id/posts', localize: true
  put :update_post, '/chefs/:id/posts/:post_id', localize: true
end

Actually calling any of the other methods, like `Chef.all`, triggers the same error on this line:
`put :update_post, '/chefs/:id/posts/:post_id', localize: true`

**Comment by lsarni** [comment]
Thanks, I ended up placing it on a different file and it work.
