### ISSUE TITLE
How to disable https verification for self-signed certificate

### ISSUE THREAD

**Issue by emanzx** [flexirest/flexirest#111]
I using flexirest to connect to my API and to secure the API communication I try to use self signed certificate https. Well I can actually use CA signed certificate but it a hassle as the API communication is based on IP address and mostly local network. Is there a way to disable the SSL verification? I have check with faraday it should be able to disable the ssl check. but going thru the flexirest document does not yield me anything. While googling about the topic also does not yield anything good. 

Here is the error I got. 

```
Faraday::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed
	from /usr/local/lib/ruby/2.4/net/protocol.rb:44:in `connect_nonblock'
	from /usr/local/lib/ruby/2.4/net/protocol.rb:44:in `ssl_socket_connect'
	from /usr/local/lib/ruby/2.4/net/http.rb:948:in `connect'
	from /usr/local/lib/ruby/2.4/net/http.rb:887:in `do_start'
	from /usr/local/lib/ruby/2.4/net/http.rb:876:in `start'
	from /usr/local/lib/ruby/2.4/net/http.rb:1407:in `request'
	from /usr/local/lib/ruby/2.4/net/http.rb:1165:in `get'
	from /usr/local/lib/ruby/gems/2.4/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:85:in `perform_request'
	from /usr/local/lib/ruby/gems/2.4/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:43:in `block in call'
	from /usr/local/lib/ruby/gems/2.4/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
	from /usr/local/lib/ruby/gems/2.4/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:38:in `call'
	from /usr/local/lib/ruby/gems/2.4/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
	from /usr/local/lib/ruby/gems/2.4/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
	from /usr/local/lib/ruby/gems/2.4/gems/faraday-0.15.4/lib/faraday/connection.rb:138:in `get'
	from /usr/local/lib/ruby/gems/2.4/gems/flexirest-1.7.7/lib/flexirest/connection.rb:47:in `block in get'
	from /usr/local/lib/ruby/gems/2.4/gems/flexirest-1.7.7/lib/flexirest/connection.rb:26:in `make_safe_request'
	from /usr/local/lib/ruby/gems/2.4/gems/flexirest-1.7.7/lib/flexirest/connection.rb:46:in `get'
	from /usr/local/lib/ruby/gems/2.4/gems/flexirest-1.7.7/lib/flexirest/request.rb:504:in `do_request'
	from /usr/local/lib/ruby/gems/2.4/gems/flexirest-1.7.7/lib/flexirest/request.rb:223:in `block in call'
	from /usr/local/lib/ruby/gems/2.4/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `block in instrument'
	from /usr/local/lib/ruby/gems/2.4/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
	from /usr/local/lib/ruby/gems/2.4/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `instrument'
	from /usr/local/lib/ruby/gems/2.4/gems/flexirest-1.7.7/lib/flexirest/request.rb:181:in `call'
	from /usr/local/lib/ruby/gems/2.4/gems/flexirest-1.7.7/lib/flexirest/base_without_validation.rb:65:in `_request'
	from (irb):17
	from /usr/local/bin/irb:11:in `<main>'

```

All helps is much appreciated.

**Comment by andyjeffries** [comment]
Sorry for the delay in replying, you need to disable this in Faraday. There's documentation on it at https://github.com/flexirest/flexirest/blob/master/docs/faraday-configuration.md but basically in your code some place you need to do:

```ruby
Flexirest::Base.faraday_config do |faraday|
  faraday.adapter(:net_http)
  faraday.ssl.verify = false
end
```
